version: '3.8'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  api:
    build:
        context: .
        dockerfile: Dockerfile
    restart: always
    ports:
      - "8123:8123"
    depends_on:
      - db

volumes:
  mariadb_data:
    driver: local
